export const ACTIONS = {
	ADD_PETS: "ADD_PETS",
	ADD_PET: "ADD_PET",
	DELETE_PET: "DELETE_PET",
	ADD_POSTS: "ADD_POSTS",
  ADD_POST: "ADD_POST",
  DELETE_POST: "DELETE_POST",
	REGISTER_FAILURE: "REGISTER_FAILURE",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
 };
 